import {mountTextStyle} from './text-style-ui.js';
import {confirmAction} from '../../packages/embed/src/confirm.js';
import {mountPresentation} from './presentation-ui.js';
import {buildPresentationPrompt,presentationIssues} from '../../packages/core/src/presentation-core.js';
import {imageTypes,defaults,parseMode,imageTarget,imageIssues,buildImagePrompt} from '../../packages/core/src/image-core.js';
import {scenarios,formats,buildPrompt} from '../../packages/core/src/core.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);
let mode=parseMode(params.get('mode')),imageType='infographic';
let scenario='analysis',format='Подобрать по задаче',promptText='',pending=null,toastTimer;
const ids=['task','role','audience','context','tone','detail','facts','missing','freedom','documentType','goal','sample','limits'];
let theme='light';try{theme=localStorage.getItem('prompt-constructor-theme')||'light';}catch{}if(['light','dark'].includes(params.get('theme')))theme=params.get('theme');
function applyTheme(){document.body.classList.toggle('dark',theme==='dark');$('theme').setAttribute('aria-label',theme==='dark'?'Включить светлую тему':'Включить тёмную тему');}applyTheme();
$('theme').onclick=()=>{theme=theme==='dark'?'light':'dark';applyTheme();try{localStorage.setItem('prompt-constructor-theme',theme);}catch{}};
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').style.display='block';toastTimer=setTimeout(()=>$('toast').style.display='none',4000);}
const textStyle=mountTextStyle(render);document.getElementById('text-editor').append(textStyle.panel);
const presentation=mountPresentation(render,toast);
document.querySelector('.workspace').insertBefore(presentation.panel,document.querySelector('.preview'));
const modes=['text','image','presentation'];
const tab=document.createElement('button');tab.id='tab-presentation';tab.role='tab';tab.textContent='Презентации';tab.setAttribute('aria-controls','presentation-editor');tab.setAttribute('aria-selected','false');tab.tabIndex=-1;document.querySelector('.mode-tabs').append(tab);
presentation.update();
function target(){return mode==='presentation'?'presentation':mode==='text'?'text':imageTarget(imageState());}
function state(){const s={format,scenario,documentStyle:textStyle.state()};for(const id of ids)s[id]=$(id).type==='checkbox'?$(id).checked:$(id).value;return s;}
function render(){const s=state(),parts=mode==='presentation'?buildPresentationPrompt(presentation.state()):mode==='image'?buildImagePrompt(imageState()):buildPrompt(s);$('context-summary').textContent=s.context.trim()?s.context.length+' симв.':'Необязательно';$('document-fields').hidden=scenario!=='document';$('guard-summary').textContent=({ask:'Уточнения — только когда без них нельзя решить задачу',draft:'Сначала черновик; недостающие факты будут отмечены',interview:'Перед ответом ИИ задаст уточняющие вопросы'})[s.missing];promptText=parts.map(([h,t])=>h.toUpperCase()+'\n'+t).join('\n\n');$('prompt').replaceChildren();parts.forEach(([h,t],i)=>{const b=document.createElement('b');b.textContent=h.toUpperCase();$('prompt').append(b,document.createTextNode('\n'+t+(i<parts.length-1?'\n\n':'')));});const issues=mode==='presentation'?Object.values(presentationIssues(presentation.state())):mode==='image'?imageIssues(imageState()):[];const ok=promptText.length<=50000&&(mode==='text'?!!s.task.trim():issues.length===0);$('image-validation').textContent=issues.join(' ');$('output-target').textContent=mode==='presentation'?'Презентация · задание на создание':mode==='text'?'Текстовый запрос':imageTarget(imageState())==='svg'?'Точная визуализация · SVG':'Генерация изображения';for(const id of ['copy','download','transfer'])$(id).disabled=!ok||!!pending;$('ready').textContent=ok?'Готов к переносу':'Нужны вводные';$('count').textContent=promptText.length.toLocaleString('ru-RU')+' символов';$('hint').textContent=promptText.length>50000?'Сократите вводные: промпт превышает 50 000 символов.':pending?'Ожидаем подтверждение от приложения…':ok?'Промпт обновляется при изменении настроек.':(issues[0]||'Заполните задачу, чтобы передать промпт в приложение.');document.querySelectorAll('[data-scenario]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.scenario===scenario));document.querySelectorAll('[data-format]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.format===format));}
const scenarioIcons={summary:'M4 5h16M4 10h16M4 15h10M4 20h7',document:'M6 3h8l4 4v14H6z M14 3v5h4 M9 12h6m-6 4h6',analysis:'M4 19V9m8 10V4m8 15v-7',text:'M4 5h16M4 10h16M4 15h10M4 20h7',letter:'M3 5h18v14H3z m0 0 9 8 9-8',plan:'M9 5h12M9 12h12M9 19h12M3 5h1M3 12h1M3 19h1',ideas:'M9 18h6m-6 3h6M8 15a7 7 0 1 1 8 0v3H8z',learning:'M3 4h7l2 2 2-2h7v15h-7l-2 2-2-2H3z M12 6v15'};
scenarios.forEach(([id,symbol,title,role,f])=>{const b=document.createElement('button');b.className='scenario';b.dataset.scenario=id;const icon=document.createElementNS('http://www.w3.org/2000/svg','svg');icon.setAttribute('viewBox','0 0 24 24');icon.innerHTML='<path d="'+scenarioIcons[id]+'"/>';b.append(icon,document.createTextNode(title));b.onclick=()=>{const oldRole=scenarios.find(x=>x[0]===scenario)?.[3];if($('role').value===oldRole)$('role').value=role;scenario=id;render();};$('scenarios').append(b);});
formats.forEach(f=>{const b=document.createElement('button');b.className='chip';b.textContent=f;b.dataset.format=f;b.onclick=()=>{format=f;render();};$('formats').append(b);});ids.forEach(id=>$(id).addEventListener('input',render));render();
$('reset').onclick=async()=>{if(mode==='presentation'){if(!await confirmAction('Сбросить параметры презентации?'))return;presentation.reset();render();return;}if(mode==='image'){if(!await confirmAction('Сбросить настройки изображения?'))return;imageType=defaults.type;for(const [k,v] of Object.entries(defaults))if($('im-'+k))$('im-'+k).value=v;updateImageUI();render();return;}if(($('task').value||$('context').value)&&!await confirmAction('Очистить задачу и все настройки?'))return;textStyle.reset();scenario='analysis';format='Подобрать по задаче';for(const id of ['task','context','limits','goal','sample'])$(id).value='';$('role').value='Бизнес-аналитик';$('audience').value='';$('tone').selectedIndex=0;$('detail').selectedIndex=1;$('facts').checked=true;$('missing').value='ask';$('freedom').value='balanced';$('documentType').selectedIndex=0;$('context-details').open=false;$('advanced').open=false;render();};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(promptText);toast('Промпт скопирован');}catch{const range=document.createRange();range.selectNodeContents($('prompt'));getSelection().removeAllRanges();getSelection().addRange(range);toast('Буфер обмена недоступен. Текст выделен — нажмите Ctrl+C.');}};
$('download').onclick=()=>{const url=URL.createObjectURL(new Blob([promptText],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='prompt-constructor.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);};
let parentOrigin=null;try{const raw=params.get('parentOrigin');if(raw&&/^https?:$/.test(new URL(raw).protocol))parentOrigin=new URL(raw).origin;}catch{}
$('transfer').onclick=()=>{
 if(pending||promptText.length>50000||(mode==='presentation'?Object.keys(presentationIssues(presentation.state())).length:mode==='text'?!state().task.trim():imageIssues(imageState()).length))return;
 if(!parentOrigin||parent===window){toast('Связь с приложением не настроена. Скопируйте промпт.');return;}
 const requestId=crypto.randomUUID();
 pending={requestId,timer:setTimeout(()=>{pending=null;render();toast('Приложение не подтвердило вставку. Проверьте черновик или скопируйте промпт.');},10000)};
 parent.postMessage({type:'prompt-constructor.prompt.insert',version:1,requestId,prompt:promptText,mode,renderTarget:target()},parentOrigin);render();
};
window.addEventListener('message',e=>{const d=e.data;if(e.source!==parent||e.origin!==parentOrigin||!pending||d?.type!=='prompt-constructor.prompt.ack'||d.version!==1||d.requestId!==pending.requestId)return;clearTimeout(pending.timer);pending=null;render();toast(d.status==='inserted'?'Промпт передан в приложение':d.status==='cancelled'?'Замена текста отменена':'Не удалось вставить промпт. Скопируйте его.');});
const examples={summary:'Сделай сводку приложенного протокола встречи: решения, открытые вопросы, ответственные и следующие шаги. Не добавляй отсутствующие в протоколе сроки.',document:'Подготовь служебную записку о запуске пилотного проекта ИИ в подразделении. Цель — согласовать состав участников и критерии оценки. Недостающие реквизиты отметь для заполнения.',analysis:'Сравни три предложения поставщиков упаковки по цене, срокам, условиям оплаты и рискам. Подготовь вывод для руководителя закупок. Если данных для выбора недостаточно, укажи, что запросить у поставщиков.',text:'Отредактируй текст отчёта: убери повторы и сложные обороты, сохрани факты и смысл. Предложи краткий заголовок и выдели основные результаты.',letter:'Подготовь письмо поставщику с просьбой уточнить сроки поставки и предоставить обновлённый график. Тон — деловой и доброжелательный.',plan:'Подготовь план пилотного внедрения ИИ-инструмента в подразделении на четыре недели. Укажи этапы, ответственных по ролям и критерии успешности.',ideas:'Предложи пять способов сократить ручную работу при подготовке еженедельного отчёта. Для каждой идеи оцени необходимые данные, усилия и ожидаемую пользу.',learning:'Подготовь короткую инструкцию для сотрудников: как составить понятный запрос к ИИ. Добавь пример и список типичных ошибок.'};
$('example').onclick=async()=>{if($('task').value.trim()&&!await confirmAction('Заменить вашу задачу примером?'))return;$('task').value=examples[scenario];render();$('task').focus();};

function imageState(){const s={...defaults,type:imageType};for(const k of Object.keys(defaults)){const el=$('im-'+k);if(el)s[k]=el.value;}if(!s.style.trim())s.style=defaults.style;if(!s.composition.trim())s.composition=defaults.composition;return s;}
function updateImageUI(){const s=imageState(),dataType=['chart','infographic'].includes(imageType);$('precision-fields').hidden=!dataType;$('chart-fields').hidden=imageType!=='chart';$('marketing-fields').hidden=imageType!=='advert';$('missing-data-fields').hidden=!!s.data.trim();const exact=imageTarget(s)==='svg';$('im-textMode').disabled=exact;$('caption-fields').hidden=!exact&&s.textMode==='none';$('variant-summary').textContent=s.variants+' вар.';document.querySelectorAll('[data-image-type]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.imageType===imageType));}
function switchMode(next){if(pending){toast('Дождитесь подтверждения переноса');return;}mode=parseMode(next);$('text-editor').hidden=mode!=='text';$('image-editor').hidden=mode!=='image';presentation.panel.hidden=mode!=='presentation';presentation.update();for(const m of modes){$('tab-'+m).setAttribute('aria-selected',m===mode);$('tab-'+m).tabIndex=m===mode?0:-1;}const url=new URL(location.href);url.searchParams.set('mode',mode);history.replaceState(null,'',url);updateImageUI();render();}
for(const m of modes){$('tab-'+m).onclick=()=>switchMode(m);$('tab-'+m).onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?modes[0]:e.key==='End'?modes.at(-1):modes[(modes.indexOf(mode)+(e.key==='ArrowRight'?1:-1)+modes.length)%modes.length];switchMode(next);$('tab-'+mode).focus();}};}
imageTypes.forEach(([id,label])=>{const b=document.createElement('button');b.className='scenario';b.dataset.imageType=id;b.textContent=label;b.onclick=()=>{imageType=id;updateImageUI();render();};$('image-types').append(b);});
Object.keys(defaults).forEach(k=>{const el=$('im-'+k);if(el)el.addEventListener('input',()=>{updateImageUI();render();});});
$('image-example').onclick=async()=>{if($('im-subject').value.trim()&&!await confirmAction('Заменить содержание и данные примером?'))return;const examples={infographic:['Покажи путь заказа от оформления до доставки в пяти последовательных этапах.','Заказ → Проверка → Комплектация → Передача в доставку → Получение'],chart:['Сравни объёмы выпуска по трём месяцам. Демонстрационные данные.','Месяц; Выпуск, тонн\nЯнварь; 120\nФевраль; 135\nМарт; 150'],poster:['Постер для внутреннего дня инноваций: один абстрактный визуальный акцент, зона для заголовка и даты.',''],cover:['Заставка презентации о цифровизации производства: современная производственная линия справа, свободное пространство для заголовка слева.',''],illustration:['Деловая иллюстрация процесса совместной работы человека и ИИ: три смысловых блока — задача, анализ, результат.',''],advert:['Рекламное изображение продукта по приложенному референсу: продукт крупно, спокойный фон и зона для короткого предложения.','']};$('im-subject').value=examples[imageType][0];$('im-data').value=examples[imageType][1];updateImageUI();render();};
switchMode(mode);

window.addEventListener('message',event=>{
 if(event.source!==parent||event.origin!==parentOrigin||event.data?.type!=='prompt-constructor.prompt.configure'||event.data.version!==1)return;
 if(['light','dark'].includes(event.data.theme)){theme=event.data.theme;applyTheme();}
 if(modes.includes(event.data.mode))switchMode(event.data.mode);
});
document.addEventListener('keydown',event=>{
 if(event.key==='Escape'&&parent!==window&&parentOrigin){event.preventDefault();parent.postMessage({type:'prompt-constructor.prompt.close',version:1},parentOrigin);}
});

function resizeFields(){document.querySelectorAll('textarea').forEach(el=>{if(el.offsetParent!==null){el.style.height='auto';el.style.height=Math.max(90,el.scrollHeight)+'px';}});}
document.addEventListener('input',resizeFields);window.addEventListener('resize',resizeFields);resizeFields();
for(const id of ['theme','reset','tab-text','tab-image','example','image-example'])$(id).disabled=false;
